name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test-algorithm-cc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: system-features = nixos-test benchmark big-parallel kvm
      - uses: cachix/cachix-action@v12
        with:
          name: shikanime
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Generate CMake project
        run: nix develop -c cmake --preset unknown-unknown-gnu -B out/build/unknown-unknown-gnu
        working-directory: algorithm-cc
      - name: Build CMake project
        run: nix develop -c cmake --build out/build/unknown-unknown-gnu
        working-directory: algorithm-cc
      - name: Run tests
        run: nix develop -c ctest --preset unknown-unknown-gnu --test-dir out/build/unknown-unknown-gnu
        working-directory: algorithm-cc
  test-algorithm-javascript:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: system-features = nixos-test benchmark big-parallel kvm
      - uses: cachix/cachix-action@v12
        with:
          name: shikanime
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Install dependencies
        run: nix develop -c npm ci
        working-directory: algorithm-javascript
      - name: Run tests
        run: nix develop -c npm run test -- --ci --passWithNoTests
        working-directory: algorithm-javascript
  test-algorithm-elixir:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: system-features = nixos-test benchmark big-parallel kvm
      - uses: cachix/cachix-action@v12
        with:
          name: shikanime
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Install dependencies
        run: nix develop -c mix deps.get
        working-directory: algorithm-elixir
      - name: Run tests
        run: nix develop -c mix test
        working-directory: algorithm-elixir
  test-algorithm-python:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: system-features = nixos-test benchmark big-parallel kvm
      - uses: cachix/cachix-action@v12
        with:
          name: shikanime
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Install dependencies
        run: nix develop -c poetry install
        working-directory: algorithm-python
      - name: Run tests
        run: nix develop -c poetry run pytest
        working-directory: algorithm-python
