name: CI
on:
  push:
    branches:
      - main
jobs:
  test-algorithm-cc:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Prepare build environment
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: system-features = nixos-test benchmark big-parallel kvm
      - name: Connect Shikanime Nix cache
        uses: cachix/cachix-action@v12
        with:
          name: shikanime
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build
        run: nix build .#algorithm-cc
        working-directory: algorithm-cc
  test-algorithm-javascript:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Prepare build environment
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: system-features = nixos-test benchmark big-parallel kvm
      - name: Connect Shikanime Nix cache
        uses: cachix/cachix-action@v12
        with:
          name: shikanime
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Install dependencies
        run: nix develop -c npm ci
        working-directory: algorithm-javascript
      - name: Run tests
        run: nix develop -c npm run test -- --ci --passWithNoTests
        working-directory: algorithm-javascript
  test-algorithm-elixir:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Prepare build environment
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: system-features = nixos-test benchmark big-parallel kvm
      - name: Connect Shikanime Nix cache
        uses: cachix/cachix-action@v12
        with:
          name: shikanime
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Install dependencies
        run: nix develop -c mix deps.get
        working-directory: algorithm-elixir
      - name: Run tests
        run: nix develop -c mix test
        working-directory: algorithm-elixir
  test-algorithm-python:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Prepare build environment
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: system-features = nixos-test benchmark big-parallel kvm
      - name: Connect Shikanime Nix cache
        uses: cachix/cachix-action@v12
        with:
          name: shikanime
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Install dependencies
        run: nix develop -c poetry install
        working-directory: algorithm-python
      - name: Run tests
        run: nix develop -c poetry run pytest
        working-directory: algorithm-python
