name: Land
on:
  issue_comment:
    types:
      - created
jobs:
  land:
    runs-on: ubuntu-latest
    steps:
      - id: createGithubAppToken
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.OPERATOR_APP_ID }}
          private-key: ${{ secrets.OPERATOR_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.createGithubAppToken.outputs.token }}
      - uses: DeterminateSystems/nix-installer-action@v17
        with:
          github-token: ${{ steps.createGithubAppToken.outputs.token }}
      - uses: DeterminateSystems/magic-nix-cache-action@v9
      - uses: shikanime/ghstack-action@v2
        with:
          token: ${{ steps.createGithubAppToken.outputs.token }}
          sign-commits: true
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
