name: Packages
on:
  workflow_run:
    workflows:
      - check
    branches:
      - main
    types:
      - completed
jobs:
  algorithm-cc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: DeterminateSystems/nix-installer-action@v19
        with:
          github-token: ${{ secrets.NIX_GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - name: Generate CMake project
        run: nix develop .#cc --impure -c cmake --preset unknown-unknown-gnu -B out/build/unknown-unknown-gnu
        working-directory: algorithm-cc
      - name: Build CMake project
        run: nix develop .#cc --impure -c cmake --build out/build/unknown-unknown-gnu
        working-directory: algorithm-cc
      - name: Run tests
        run: nix develop .#cc --impure -c ctest --preset unknown-unknown-gnu --test-dir out/build/unknown-unknown-gnu
        working-directory: algorithm-cc
  algorithm-javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: DeterminateSystems/nix-installer-action@v19
        with:
          github-token: ${{ secrets.NIX_GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - name: Install dependencies
        run: nix develop .#javascript --impure -c npm ci
        working-directory: algorithm-javascript
      - name: Run tests
        run: nix develop .#javascript --impure -c npm run test -- --ci --passWithNoTests
        working-directory: algorithm-javascript
  algorithm-beam:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: DeterminateSystems/nix-installer-action@v19
        with:
          github-token: ${{ secrets.NIX_GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - name: Install dependencies
        run: nix develop .#beam --impure -c mix deps.get
        working-directory: algorithm-beam
      - name: Run tests
        run: nix develop .#beam --impure -c mix test
        working-directory: algorithm-beam
  algorithm-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: DeterminateSystems/nix-installer-action@v19
        with:
          github-token: ${{ secrets.NIX_GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - name: Run tests
        run: nix develop .#python --impure -c uv run pytest
        working-directory: algorithm-python
