name: Update
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - id: createGithubAppToken
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.OPERATOR_APP_ID }}
          private-key: ${{ secrets.OPERATOR_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.createGithubAppToken.outputs.token }}
      - uses: DeterminateSystems/nix-installer-action@v17
        with:
          github-token: ${{ steps.createGithubAppToken.outputs.token }}
      - uses: DeterminateSystems/magic-nix-cache-action@v9
      - uses: DeterminateSystems/update-flake-lock@v25
        with:
          branch: github/update_flake
          commit-msg: Update Flake
          pr-title: Update Flake
          pr-labels: dependencies
          pr-assignees: shikanime
          sign-commits: true
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
